pool: 
  vmImage: "Ubuntu 16.04"
steps: 
  - 
    bash: "echo use Mix.Config >> ./chip_api/config/dev.secret.exs"
    displayName: Mix.Config
  - 
      bash: "echo config :chip_api, ChipApi.Repo, password:$(pgPassword) >> ./chip_api/config/dev.secret.exs"
      displayName: "config chip_api dev"
  - 
      bash: "echo use Mix.Config >> ./chip_api/config/test.secret.exs"
      displayName: Mix.Config
  - 
      bash: "echo config :chip_api, ChipApi.Repo, password:$(pgPassword) >> ./chip_api/config/test.secret.exs"
      displayName: "config chip_api test"
  - 
      bash: "docker build ./chip_app -t $(registryName).azurecr.io/$(frontImageUat)"
      displayName: "docker build frontImageUat"
  - 
      bash: "docker build ./chip_api -t $(registryName).azurecr.io/$(apiImageUat)"
      displayName: "docker build apiImageUat"
  - 
      bash: "docker login $(registryName).azurecr.io -u $(registryName) -p $(registryPassword)"
      displayName: "docker login acr"
  - 
      bash: "docker push $(registryName).azurecr.io/$(frontImageUat)"
      displayName: "docker push frontImageUat"
  - 
      bash: "docker push $(registryName).azurecr.io/$(apiImageUat)"
      displayName: "docker push apiImageUat"
variables: 
    - 
      group: CCC-ACR
    - 
      group: CCC-PostgreSQL
    -
      group: cccp-uat

trigger:
  - uat
