pool:
  vmImage: 'Ubuntu 16.04'


variables:
  # registryServerName, ImageName, projectName, registryName, registryLogin and registryPassword in the build pipeline in UI
- group: cccpVariableGroup

steps:
- bash: echo use Mix.Config >> ./chip_api/config/dev.secret.exs
  displayName: 'Mix.Config'

- bash: echo config :chip_api, ChipApi.Repo, password: $(pgPassword) >> ./chip_api/config/dev.secret.exs
  displayName: 'config chip_api dev'

- bash: echo use Mix.Config >> ./chip_api/config/test.secret.exs
  displayName: 'Mix.Config'

- bash: echo config :chip_api, ChipApi.Repo, password: $(pgPassword) >> ./chip_api/config/test.secret.exs
  displayName: 'config chip_api test'

- bash: docker build ./chip_app -t $(registryName).azurecr.io/$(frontImageName)
  displayName: 'docker build frontImageName'

- bash: docker build ./chip_api -t $(registryName).azurecr.io/$(apiImageName)
  displayName: 'docker build apiImageName'

-bash: docker login $(registryName).azurecr.io -u $(registryName) -p $(registryPassword)
  displayName: 'docker login acr'

- bash: docker push $(registryName).azurecr.io/$(frontImageName)
  displayName: 'docker push frontImageName'

- bash: docker push $(registryName).azurecr.io/$(apiImageName)
  displayName: 'docker push apiImageName'

trigger:
- master
- dev
# - features/*

# Reference: https://github.com/Azure/phippyandfriends/blob/master/azure-build-pipeline.yml