pool: 
  vmImage: "Ubuntu 16.04"
steps: 
  - 
    bash: "echo use Mix.Config >> ./chip_api/config/dev.secret.exs"
    displayName: Mix.Config
  - 
      bash: "echo config :chip_api, ChipApi.Repo, password:$(pgPassword) >> ./chip_api/config/dev.secret.exs"
      displayName: "config chip_api dev"
  - 
      bash: "echo use Mix.Config >> ./chip_api/config/test.secret.exs"
      displayName: Mix.Config
  - 
      bash: "echo config :chip_api, ChipApi.Repo, password:$(pgPassword) >> ./chip_api/config/test.secret.exs"
      displayName: "config chip_api test"
  - 
      bash: "docker build ./chip_app -t $(registryName).azurecr.io/$(frontImage)$(Build.SourceBranchName)"
      displayName: "docker build frontImage"
  - 
      bash: "docker build ./chip_api -t $(registryName).azurecr.io/$(apiImage)$(Build.SourceBranchName)"
      displayName: "docker build apiImage"
  - 
      bash: "docker login $(registryName).azurecr.io -u $(registryName) -p $(registryPassword)"
      displayName: "docker login acr"
  - 
      bash: "docker push $(registryName).azurecr.io/$(frontImage)$(Build.SourceBranchName)"
      displayName: "docker push frontImage"
  - 
      bash: "docker push $(registryName).azurecr.io/$(apiImage)$(Build.SourceBranchName)"
      displayName: "docker push apiImage"
variables: 
    - 
      group: CCC-ACR
    - 
      group: CCC-PostgreSQL
    -
      group: cccp-images

trigger:
  - master
  - uat
  - dev