version: "3.1"

services:

  cccpfrontdev:
    container_name: cccpfrontdev
    build: "./chip_app"
    image: ccccontainers.azurecr.io/cccp-front:latest
    depends_on:
      - cccpdb
      - cccpapidev
    ports:
      - 3002:3002
    
  cccpapidev:
    container_name: cccpapidev
    build: "./chip_api"
    image: ccccontainers.azurecr.io/cccp-api:latest
    depends_on:
      - cccpdb
    ports:
      - 9000:9000

  cccpdb:
    container_name: cccpdb
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "chip_dev"

volumes:
  pgdata:
