version: '3'
services:
  front:
    build: ./chip_app
    ports:
     - "3000:3000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "test123"
    ports:
     - "8081:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8081