version: "3.1"

services:

  cccpfront:
    container_name: cccpfront
    build: "./chip_app"
    image: ccccontainers.azurecr.io/cccp-front:v1
    depends_on:
      - cccpdb
      - cccpapi
    ports:
      - 3000:3000
    
  cccpapi:
    container_name: cccpapi
    build: "./chip_api"
    image: ccccontainers.azurecr.io/cccp-api:v1
    depends_on:
      - cccpdb
    ports:
      - 4000:4000

  cccpdb:
    container_name: cccpdb
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "chip_dev"

volumes:
  pgdata:
