version: '3.1'

services:

  front:
    container_name: front
    build: "./chip_app"
    image: ccccontainers.azurecr.io/front:latest
    depends_on:
      - db
      - api
    ports:
      - 3000:3000
    
  api:
    container_name: api
    build: "./chip_api"
    image: ccccontainers.azurecr.io/api:latest
    depends_on:
      - db
    ports:
      - 4000:4000

  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "chip_dev"

  admin:
    container_name: admin
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
