version: "3.1"

services:

  cccpfrontuat:
    container_name: cccpfrontuat
    build: "./chip_app"
    image: ccccontainers.azurecr.io/cccp-front:latest
    depends_on:
      - cccpdb
      - cccpapiuat
    ports:
      - 3002:80
    volumes:
      - ./chip_app/src:/app/src:rw
      - ./chip_app/.env:/app/.env:rw
    
  cccpapiuat:
    container_name: cccpapiuat
    build: "./chip_api"
    image: ccccontainers.azurecr.io/cccp-api:latest
    depends_on:
      - cccpdb
    ports:
      - 9001:9001

  cccpdb:
    container_name: cccpdb
    image: postgres:11
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "chip_dev"

volumes:
  pgdata:
