apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\Users\pdetjens\kompose.exe convert -f docker-compose.yml -o
        kubernetes-compose.yml
      kompose.version: 1.19.0 (f63a961c)
    creationTimestamp: null
    labels:
<<<<<<< HEAD
      io.kompose.service: cccpapidev
    name: cccpapidev
  spec:
    ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    selector:
      io.kompose.service: cccpapidev
=======
      io.kompose.service: cccpapiuat
    name: cccpapiuat
  spec:
    ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
    selector:
      io.kompose.service: cccpapiuat
>>>>>>> master
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\Users\pdetjens\kompose.exe convert -f docker-compose.yml -o
        kubernetes-compose.yml
      kompose.version: 1.19.0 (f63a961c)
    creationTimestamp: null
    labels:
<<<<<<< HEAD
      io.kompose.service: cccpfrontdev
    name: cccpfrontdev
=======
      io.kompose.service: cccpfrontuat
    name: cccpfrontuat
>>>>>>> master
  spec:
    ports:
    - name: "3002"
      port: 3002
      targetPort: 80
    selector:
<<<<<<< HEAD
      io.kompose.service: cccpfrontdev
=======
      io.kompose.service: cccpfrontuat
>>>>>>> master
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\Users\pdetjens\kompose.exe convert -f docker-compose.yml -o
        kubernetes-compose.yml
      kompose.version: 1.19.0 (f63a961c)
    creationTimestamp: null
    labels:
<<<<<<< HEAD
      io.kompose.service: cccpapidev
    name: cccpapidev
=======
      io.kompose.service: cccpapiuat
    name: cccpapiuat
>>>>>>> master
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: C:\Users\pdetjens\kompose.exe convert -f docker-compose.yml
            -o kubernetes-compose.yml
          kompose.version: 1.19.0 (f63a961c)
        creationTimestamp: null
        labels:
<<<<<<< HEAD
          io.kompose.service: cccpapidev
      spec:
        containers:
        - image: ccccontainers.azurecr.io/cccp-api:latest
          name: cccpapidev
          ports:
          - containerPort: 9000
=======
          io.kompose.service: cccpapiuat
      spec:
        containers:
        - image: ccccontainers.azurecr.io/cccp-api:latest
          name: cccpapiuat
          ports:
          - containerPort: 9001
>>>>>>> master
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\Users\pdetjens\kompose.exe convert -f docker-compose.yml -o
        kubernetes-compose.yml
      kompose.version: 1.19.0 (f63a961c)
    creationTimestamp: null
    labels:
      io.kompose.service: cccpdb
    name: cccpdb
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          kompose.cmd: C:\Users\pdetjens\kompose.exe convert -f docker-compose.yml
            -o kubernetes-compose.yml
          kompose.version: 1.19.0 (f63a961c)
        creationTimestamp: null
        labels:
          io.kompose.service: cccpdb
      spec:
        containers:
        - env:
          - name: POSTGRES_PASSWORD
            value: chip_dev
          image: postgres:11
          imagePullPolicy: IfNotPresent
          name: cccpdb
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pgdata
        restartPolicy: Always
        volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: pgdata
    name: pgdata
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\Users\pdetjens\kompose.exe convert -f docker-compose.yml -o
        kubernetes-compose.yml
      kompose.version: 1.19.0 (f63a961c)
    creationTimestamp: null
    labels:
<<<<<<< HEAD
      io.kompose.service: cccpfrontdev
    name: cccpfrontdev
=======
      io.kompose.service: cccpfrontuat
    name: cccpfrontuat
>>>>>>> master
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: C:\Users\pdetjens\kompose.exe convert -f docker-compose.yml
            -o kubernetes-compose.yml
          kompose.version: 1.19.0 (f63a961c)
        creationTimestamp: null
        labels:
<<<<<<< HEAD
          io.kompose.service: cccpfrontdev
      spec:
        containers:
        - image: ccccontainers.azurecr.io/cccp-front:latest
          name: cccpfrontdev
=======
          io.kompose.service: cccpfrontuat
      spec:
        containers:
        - image: ccccontainers.azurecr.io/cccp-front:latest
          name: cccpfrontuat
>>>>>>> master
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

