-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ChipApi.Object.AdaptationStrategy exposing (..)

import ChipApi.InputObject
import ChipApi.Interface
import ChipApi.Object
import ChipApi.Scalar
import ChipApi.ScalarCodecs
import ChipApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The advantages that are associated with the strategy
-}
advantages :
    SelectionSet decodesTo ChipApi.Object.AdaptationAdvantages
    -> SelectionSet (List decodesTo) ChipApi.Object.AdaptationStrategy
advantages object____ =
    Object.selectionForCompositeField "advantages" [] object____ (Basics.identity >> Decode.list)


{-| Applicability description
-}
applicability : SelectionSet (Maybe String) ChipApi.Object.AdaptationStrategy
applicability =
    Object.selectionForField "(Maybe String)" "applicability" [] (Decode.string |> Decode.nullable)


{-| The impact in meters on beach width this strategy generally has
-}
beachWidthImpactM : SelectionSet (Maybe Float) ChipApi.Object.AdaptationStrategy
beachWidthImpactM =
    Object.selectionForField "(Maybe Float)" "beachWidthImpactM" [] (Decode.float |> Decode.nullable)


{-| The adaptation benefits that are associated with the strategy
-}
benefits :
    SelectionSet decodesTo ChipApi.Object.AdaptationBenefit
    -> SelectionSet (List decodesTo) ChipApi.Object.AdaptationStrategy
benefits object____ =
    Object.selectionForCompositeField "benefits" [] object____ (Basics.identity >> Decode.list)


{-| The adaptation categories that are associated with the strategy
-}
categories :
    SelectionSet decodesTo ChipApi.Object.AdaptationCategory
    -> SelectionSet (List decodesTo) ChipApi.Object.AdaptationStrategy
categories object____ =
    Object.selectionForCompositeField "categories" [] object____ (Basics.identity >> Decode.list)


{-| The ordinal cost category as it pertains to cost per length of the strategy
-}
costs :
    SelectionSet decodesTo ChipApi.Object.ImpactCost
    -> SelectionSet (List decodesTo) ChipApi.Object.AdaptationStrategy
costs object____ =
    Object.selectionForCompositeField "costs" [] object____ (Basics.identity >> Decode.list)


{-| The currently permittable status of the strategy
-}
currentlyPermittable : SelectionSet (Maybe String) ChipApi.Object.AdaptationStrategy
currentlyPermittable =
    Object.selectionForField "(Maybe String)" "currentlyPermittable" [] (Decode.string |> Decode.nullable)


{-| The description of the strategy
-}
description : SelectionSet (Maybe String) ChipApi.Object.AdaptationStrategy
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The disadvantages that are associated with the strategy
-}
disadvantages :
    SelectionSet decodesTo ChipApi.Object.AdaptationDisadvantages
    -> SelectionSet (List decodesTo) ChipApi.Object.AdaptationStrategy
disadvantages object____ =
    Object.selectionForCompositeField "disadvantages" [] object____ (Basics.identity >> Decode.list)


{-| The coastal hazards that the strategy helps mitigate
-}
hazards :
    SelectionSet decodesTo ChipApi.Object.CoastalHazard
    -> SelectionSet (List decodesTo) ChipApi.Object.AdaptationStrategy
hazards object____ =
    Object.selectionForCompositeField "hazards" [] object____ (Basics.identity >> Decode.list)


{-| The ID of the strategy
-}
id : SelectionSet ChipApi.ScalarCodecs.Id ChipApi.Object.AdaptationStrategy
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (ChipApi.ScalarCodecs.codecs |> ChipApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The server path to an image of the adaptation strategy
-}
imagePath : SelectionSet (Maybe String) ChipApi.Object.AdaptationStrategy
imagePath =
    Object.selectionForField "(Maybe String)" "imagePath" [] (Decode.string |> Decode.nullable)


{-| Denotes whether this strategy is currently available for planning
-}
isActive : SelectionSet Bool ChipApi.Object.AdaptationStrategy
isActive =
    Object.selectionForField "Bool" "isActive" [] Decode.bool


{-| The ordinal life span category of the strategy
-}
lifeSpans :
    SelectionSet decodesTo ChipApi.Object.ImpactLifeSpan
    -> SelectionSet (List decodesTo) ChipApi.Object.AdaptationStrategy
lifeSpans object____ =
    Object.selectionForCompositeField "lifeSpans" [] object____ (Basics.identity >> Decode.list)


{-| The name of the strategy
-}
name : SelectionSet String ChipApi.Object.AdaptationStrategy
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The geographic scales of impact the strategy can target
-}
scales :
    SelectionSet decodesTo ChipApi.Object.ImpactScale
    -> SelectionSet (List decodesTo) ChipApi.Object.AdaptationStrategy
scales object____ =
    Object.selectionForCompositeField "scales" [] object____ (Basics.identity >> Decode.list)


{-| Description of valid placement the strategy can be used in
-}
strategyPlacement : SelectionSet (Maybe String) ChipApi.Object.AdaptationStrategy
strategyPlacement =
    Object.selectionForField "(Maybe String)" "strategyPlacement" [] (Decode.string |> Decode.nullable)
