-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module ChipApi.Object.AdaptationStrategy exposing (..)

import ChipApi.InputObject
import ChipApi.Interface
import ChipApi.Object
import ChipApi.Scalar
import ChipApi.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) ChipApi.Object.AdaptationStrategy
selection constructor =
    Object.selection constructor


{-| The adaptation categories that are associated with the strategy
-}
categories : SelectionSet decodesTo ChipApi.Object.AdaptationCategory -> Field (Maybe (List (Maybe decodesTo))) ChipApi.Object.AdaptationStrategy
categories object =
    Object.selectionField "categories" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| The description of the strategy
-}
description : Field (Maybe String) ChipApi.Object.AdaptationStrategy
description =
    Object.fieldDecoder "description" [] (Decode.string |> Decode.nullable)


{-| The coastal hazards that the strategy helps mitigate
-}
hazards : SelectionSet decodesTo ChipApi.Object.CoastalHazard -> Field (Maybe (List (Maybe decodesTo))) ChipApi.Object.AdaptationStrategy
hazards object =
    Object.selectionField "hazards" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Denotes whether this strategy is currently available for planning
-}
isActive : Field (Maybe Bool) ChipApi.Object.AdaptationStrategy
isActive =
    Object.fieldDecoder "isActive" [] (Decode.bool |> Decode.nullable)


{-| The name of the strategy
-}
name : Field (Maybe String) ChipApi.Object.AdaptationStrategy
name =
    Object.fieldDecoder "name" [] (Decode.string |> Decode.nullable)


{-| The geographic scales of impact the strategy can target
-}
scales : SelectionSet decodesTo ChipApi.Object.ImpactScale -> Field (Maybe (List (Maybe decodesTo))) ChipApi.Object.AdaptationStrategy
scales object =
    Object.selectionField "scales" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
