-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module ChipApi.Object.AdaptationCategory exposing (..)

import ChipApi.InputObject
import ChipApi.Interface
import ChipApi.Object
import ChipApi.Scalar
import ChipApi.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) ChipApi.Object.AdaptationCategory
selection constructor =
    Object.selection constructor


{-| The description of the category
-}
description : Field (Maybe String) ChipApi.Object.AdaptationCategory
description =
    Object.fieldDecoder "description" [] (Decode.string |> Decode.nullable)


{-| The name of the category
-}
name : Field String ChipApi.Object.AdaptationCategory
name =
    Object.fieldDecoder "name" [] Decode.string


{-| The adaptation strategies that are associated with the category
-}
strategies : SelectionSet decodesTo ChipApi.Object.AdaptationStrategy -> Field (List decodesTo) ChipApi.Object.AdaptationCategory
strategies object =
    Object.selectionField "strategies" [] object (identity >> Decode.list)
