-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ChipApi.Object.ImpactLifeSpan exposing (..)

import ChipApi.InputObject
import ChipApi.Interface
import ChipApi.Object
import ChipApi.Scalar
import ChipApi.ScalarCodecs
import ChipApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The description of the life span category
-}
description : SelectionSet (Maybe String) ChipApi.Object.ImpactLifeSpan
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The life span is an integer representing the relative scale of life span category. A larger number means a longer life span
-}
lifeSpan : SelectionSet Int ChipApi.Object.ImpactLifeSpan
lifeSpan =
    Object.selectionForField "Int" "lifeSpan" [] Decode.int


{-| The name of the life span category described qualitatively
-}
name : SelectionSet String ChipApi.Object.ImpactLifeSpan
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The adaptation strategies that are associated with the life span category
-}
strategies :
    SelectionSet decodesTo ChipApi.Object.AdaptationStrategy
    -> SelectionSet (List decodesTo) ChipApi.Object.ImpactLifeSpan
strategies object____ =
    Object.selectionForCompositeField "strategies" [] object____ (Basics.identity >> Decode.list)
