-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module ChipApi.Object.ImpactCost exposing (..)

import ChipApi.InputObject
import ChipApi.Interface
import ChipApi.Object
import ChipApi.Scalar
import ChipApi.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) ChipApi.Object.ImpactCost
selection constructor =
    Object.selection constructor


{-| The cost is an integer representing the relative scale of cost category. A larger number means a larger cost
-}
cost : Field Int ChipApi.Object.ImpactCost
cost =
    Object.fieldDecoder "cost" [] Decode.int


{-| The description of the cost category
-}
description : Field (Maybe String) ChipApi.Object.ImpactCost
description =
    Object.fieldDecoder "description" [] (Decode.string |> Decode.nullable)


{-| The name of the cost category described qualitatively
-}
name : Field String ChipApi.Object.ImpactCost
name =
    Object.fieldDecoder "name" [] Decode.string


{-| The name of the cost category described quantitatively
-}
nameLinearFoot : Field (Maybe String) ChipApi.Object.ImpactCost
nameLinearFoot =
    Object.fieldDecoder "nameLinearFoot" [] (Decode.string |> Decode.nullable)


{-| The adaptation strategies that are associated with the cost category
-}
strategies : SelectionSet decodesTo ChipApi.Object.AdaptationStrategy -> Field (List decodesTo) ChipApi.Object.ImpactCost
strategies object =
    Object.selectionField "strategies" [] object (identity >> Decode.list)
