-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ChipApi.Object.ImpactCost exposing (..)

import ChipApi.InputObject
import ChipApi.Interface
import ChipApi.Object
import ChipApi.Scalar
import ChipApi.ScalarCodecs
import ChipApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The cost is an integer representing the relative scale of cost category. A larger number means a larger cost
-}
cost : SelectionSet Int ChipApi.Object.ImpactCost
cost =
    Object.selectionForField "Int" "cost" [] Decode.int


{-| The description of the cost category
-}
description : SelectionSet (Maybe String) ChipApi.Object.ImpactCost
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The name of the cost category described qualitatively
-}
name : SelectionSet String ChipApi.Object.ImpactCost
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The name of the cost category described quantitatively
-}
nameLinearFoot : SelectionSet (Maybe String) ChipApi.Object.ImpactCost
nameLinearFoot =
    Object.selectionForField "(Maybe String)" "nameLinearFoot" [] (Decode.string |> Decode.nullable)


{-| The adaptation strategies that are associated with the cost category
-}
strategies :
    SelectionSet decodesTo ChipApi.Object.AdaptationStrategy
    -> SelectionSet (List decodesTo) ChipApi.Object.ImpactCost
strategies object____ =
    Object.selectionForCompositeField "strategies" [] object____ (Basics.identity >> Decode.list)
