-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ChipApi.Object.ImpactScale exposing (..)

import ChipApi.InputObject
import ChipApi.Interface
import ChipApi.Object
import ChipApi.Scalar
import ChipApi.ScalarCodecs
import ChipApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The description of the scale of impact
-}
description : SelectionSet (Maybe String) ChipApi.Object.ImpactScale
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The ID of the scale of impact
-}
id : SelectionSet ChipApi.ScalarCodecs.Id ChipApi.Object.ImpactScale
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (ChipApi.ScalarCodecs.codecs |> ChipApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The impact is an integer representing the relative scale of impact. A larger number means a larger scale
-}
impact : SelectionSet Int ChipApi.Object.ImpactScale
impact =
    Object.selectionForField "Int" "impact" [] Decode.int


{-| The name of the scale of impact
-}
name : SelectionSet String ChipApi.Object.ImpactScale
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The adaptation strategies that are associated with the scale of impact
-}
strategies :
    SelectionSet decodesTo ChipApi.Object.AdaptationStrategy
    -> SelectionSet (List decodesTo) ChipApi.Object.ImpactScale
strategies object____ =
    Object.selectionForCompositeField "strategies" [] object____ (Basics.identity >> Decode.list)
