-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module ChipApi.Object.ImpactLifeSpan exposing (..)

import ChipApi.InputObject
import ChipApi.Interface
import ChipApi.Object
import ChipApi.Scalar
import ChipApi.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) ChipApi.Object.ImpactLifeSpan
selection constructor =
    Object.selection constructor


{-| The description of the life span category
-}
description : Field (Maybe String) ChipApi.Object.ImpactLifeSpan
description =
    Object.fieldDecoder "description" [] (Decode.string |> Decode.nullable)


{-| The life span is an integer representing the relative scale of life span category. A larger number means a longer life span
-}
lifeSpan : Field Int ChipApi.Object.ImpactLifeSpan
lifeSpan =
    Object.fieldDecoder "lifeSpan" [] Decode.int


{-| The name of the life span category described qualitatively
-}
name : Field String ChipApi.Object.ImpactLifeSpan
name =
    Object.fieldDecoder "name" [] Decode.string


{-| The adaptation strategies that are associated with the life span category
-}
strategies : SelectionSet decodesTo ChipApi.Object.AdaptationStrategy -> Field (List decodesTo) ChipApi.Object.ImpactLifeSpan
strategies object =
    Object.selectionField "strategies" [] object (identity >> Decode.list)
