version: 2.0
jobs:
  BuildPushMaster:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            echo use Mix.Config >> ./chip_api/config/dev.secret.exs
            echo config :chip_api, ChipApi.Repo, password: "\"$PGPW\"" >> ./chip_api/config/dev.secret.exs
            echo use Mix.Config >> ./chip_api/config/test.secret.exs
            echo config :chip_api, ChipApi.Repo, password: "\"$PGPW\"" >> ./chip_api/config/test.secret.exs
            docker build ./chip_app -t ${registryName}.azurecr.io/${frontImageLatest}
            docker build ./chip_api -t ${registryName}.azurecr.io/${apiImageLatest}
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/${frontImageLatest}
            docker push ${registryName}.azurecr.io/${apiImageLatest}
  BuildPushUAT:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            echo use Mix.Config >> ./chip_api/config/dev.secret.exs
            echo config :chip_api, ChipApi.Repo, password: "\"$PGPW\"" >> ./chip_api/config/dev.secret.exs
            echo use Mix.Config >> ./chip_api/config/test.secret.exs
            echo config :chip_api, ChipApi.Repo, password: "\"$PGPW\"" >> ./chip_api/config/test.secret.exs
            docker build ./chip_app -t ${registryName}.azurecr.io/${frontImageUat}
            docker build ./chip_api -t ${registryName}.azurecr.io/${apiImageUat}
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/${frontImageUat}
            docker push ${registryName}.azurecr.io/${apiImageUat}
  BuildPushDev:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            echo use Mix.Config >> ./chip_api/config/dev.secret.exs
            echo config :chip_api, ChipApi.Repo, password: "\"$PGPW\"" >> ./chip_api/config/dev.secret.exs
            echo use Mix.Config >> ./chip_api/config/test.secret.exs
            echo config :chip_api, ChipApi.Repo, password: "\"$PGPW\"" >> ./chip_api/config/test.secret.exs
            docker build ./chip_app -t ${registryName}.azurecr.io/${frontImageDev}
            docker build ./chip_api -t ${registryName}.azurecr.io/${apiImageDev}
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/${frontImageDev}
            docker push ${registryName}.azurecr.io/${apiImageDev}
workflows:
  version: 2
  CCCP_Workflow:
    jobs:
      - BuildPushMaster:
          filters:
            branches:
              only: master
      - BuildPushUAT:
          filters:
            branches:
              only: uat
      - BuildPushDev:
          filters:
            branches:
              only: dev