-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module ChipApi.Object exposing (..)


type AdaptationCategory
    = AdaptationCategory


type AdaptationStrategy
    = AdaptationStrategy


type CoastalHazard
    = CoastalHazard


type ImpactScale
    = ImpactScale


type ShorelineLocation
    = ShorelineLocation


type StrategyPlacement
    = StrategyPlacement
