-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module ChipApi.Object exposing (..)


type AdaptationAdvantages
    = AdaptationAdvantages


type AdaptationBenefit
    = AdaptationBenefit


type AdaptationCategory
    = AdaptationCategory


type AdaptationDisadvantages
    = AdaptationDisadvantages


type AdaptationStrategy
    = AdaptationStrategy


type CoastalHazard
    = CoastalHazard


type ImpactCost
    = ImpactCost


type ImpactLifeSpan
    = ImpactLifeSpan


type ImpactScale
    = ImpactScale


type ShorelineLocation
    = ShorelineLocation
