-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ChipApi.ScalarCodecs exposing (..)

import ChipApi.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Decimal =
    ChipApi.Scalar.Decimal


type alias GeographicExtent =
    ChipApi.Scalar.GeographicExtent


type alias Id =
    ChipApi.Scalar.Id


codecs : ChipApi.Scalar.Codecs Decimal GeographicExtent Id
codecs =
    ChipApi.Scalar.defineCodecs
        { codecDecimal = defaultCodecs.codecDecimal
        , codecGeographicExtent = defaultCodecs.codecGeographicExtent
        , codecId = defaultCodecs.codecId
        }
