-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module ChipApi.Scalar exposing (..)


type GeographicExtent
    = GeographicExtent String
